#### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.


In [1]:
!pip install numpy

In [ ]:
import numpy as np

## CREATE ARRAY USING NUMPY
## CREATE A 1D ARRAY
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D ARRAY
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)  ## 1 ROW AND 5 COLUMNS

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [ ]:
## 2D ARRAY
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## IDENTITY MATRIX
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## ATTRIBUTES OF NUMPY ARRAY
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # OUTPUT: (2, 3)
print("Number of dimensions:", arr.ndim)  # OUTPUT: 2
print("Size (number of elements):", arr.size)  # OUTPUT: 6
print("Data type:", arr.dtype)  # OUTPUT: INT32 (MAY VARY BASED ON PLATFORM)
print("Item size (in bytes):", arr.itemsize)  # OUTPUT: 8 (MAY VARY BASED ON PLATFORM)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [ ]:
### NUMPY VECTORIZED OPERATION
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Addition:", arr1 + arr2)  ### ELEMENT WISE ADDITION
print("Substraction:", arr1 - arr2)  ## ELEMENT WISE SUBSTRACTION
print("Multiplication:", arr1 * arr2)  # ELEMENT-WISE MULTIPLICATION
print("Division:", arr1 / arr2)  # ELEMENT-WISE DIVISION

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## UNIVERSAL FUNCTION
arr = np.array([2, 3, 4, 5, 6])

print(np.sqrt(arr))  ## SQUARE ROOT
print(np.exp(arr))  ## EXPONENTIAL
print(np.sin(arr))  ## SINE
print(np.log(arr))  ## NATURAL LOG

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## ARRAY SLICING AND INDEXING

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# arr[row_slice, column_slice] => START FROM ROW INDEX 1 GO TILL THE END OF THE ROWS, AND SELECT COLUMNS FROM INDEX 1 TO 2 (3 IS EXCLUSIVE)
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [ ]:
print(arr[0][0])
print(arr[0:2, 2:])

1
[[3 4]
 [7 8]]


In [ ]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## MODIFY ARRAY ELEMENTS
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
### STATISTICAL CONCEPTS--NORMALIZATION
## TO HAVE A MEAN OF 0 AND STANDARD DEVIATION OF 1
data = np.array([1, 2, 3, 4, 5])

# CALCULATE THE MEAN AND STANDARD DEVIATION
mean = np.mean(data)
std_dev = np.std(data)

# NORMALIZE THE DATA
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# MEAN
mean = np.mean(data)
print("Mean:", mean)

# MEDIAN
median = np.median(data)
print("Median:", median)

# STANDARD DEVIATION
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# VARIANCE
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## LOGICAL OPERATION
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])