# Module: NumPy Assignments

## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [1]:
import numpy as np

# CREATE A NUMPY ARRAY OF SHAPE (5, 5) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# REPLACE ALL THE ELEMENTS IN THE THIRD COLUMN WITH 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[12  8  3  8 15]
 [ 5 19  6 13  1]
 [17 16  7  1 19]
 [ 3 20 18 11 15]
 [17  8 16 18 12]]
Modified array:
[[12  8  1  8 15]
 [ 5 19  1 13  1]
 [17 16  1  1 19]
 [ 3 20  1 11 15]
 [17  8  1 18 12]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [2]:
# CREATE A NUMPY ARRAY OF SHAPE (4, 4) WITH VALUES FROM 1 TO 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# REPLACE THE DIAGONAL ELEMENTS WITH 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [3]:
# CREATE A NUMPY ARRAY OF SHAPE (6, 6) WITH VALUES FROM 1 TO 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# EXTRACT THE SUB-ARRAY
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [ ]:
# # Why the examples RESHAPE WITH ARRANGE BUT SIZE WITH RANDOM
# np.arange(1, 37) → CREATES A 1D ARRAY [1, 2, 3, ..., 36]
# .reshape((6, 6)) → RESHAPES IT INTO A 6×6 2D ARRAY
# np.random.randint(1, 21) → GENERATES RANDOM INTEGERS BETWEEN 1 AND 20
# size=(5,5) → CREATES A 5×5 ARRAY
# RESHAPE IS USED TO GET THE RIGHT SHAPE FROM A 1D ARRAY;
# SIZE IN RANDOM FUNCTIONS DIRECTLY DEFINES THE SHAPE.

In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (5, 5) WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# EXTRACT THE ELEMENTS ON THE BORDER
# array[0, :] => FIRST ROW, ALL COLUMNS
# array[-1, :] => LAST ROW, ALL COLUMNS
# array[1:-1, 0] => ALL ROWS EXCEPT FIRST AND LAST, FIRST COLUMN
# array[1:-1, -1] => ALL ROWS EXCEPT FIRST AND LAST, LAST COLUMN
border_elements = np.concatenate(
    (array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1])
)
print("Border elements:")
print(border_elements)

Original array:
[[10  9 16 13 17]
 [10  6 18 16 17]
 [ 9  5 14  2 11]
 [12 13 18  3 20]
 [13  9 13 16  6]]
Border elements:
[10  9 16 13 17 13  9 13 16  6 10  9 12 17 11 20]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [ ]:
# CREATE TWO NUMPY ARRAYS OF SHAPE (3, 4) FILLED WITH RANDOM INTEGERS
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# PERFORM ELEMENT-WISE OPERATIONS
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (4, 4) WITH VALUES FROM 1 TO 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# COMPUTE THE ROW-WISE AND COLUMN-WISE SUM
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (5, 5) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# COMPUTE THE STATISTICAL VALUES
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (3, 3) WITH VALUES FROM 1 TO 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# NORMALIZE THE ARRAY
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (3, 3) FILLED WITH RANDOM INTEGERS
# size=(3, 3) MEANS IT WILL CREATE A 3x3 ARRAY, I.E., 3 ROWS AND 3 COLUMNS
# size=(3,) MEANS IT WILL CREATE A 1D ARRAY WITH 3 ELEMENTS
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# ADD THE 1D ARRAY TO EACH ROW OF THE 2D ARRAY USING BROADCASTING
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 2  3  7]
 [ 3  4  5]
 [ 6  4 10]]
1D array:
[8 1 3]
Resulting array:
[[10  4 10]
 [11  5  8]
 [14  5 13]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (4, 4) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# SUBTRACT THE 1D ARRAY FROM EACH COLUMN OF THE 2D ARRAY USING BROADCASTING
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (3, 3) REPRESENTING A MATRIX
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# COMPUTE THE DETERMINANT
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# COMPUTE THE INVERSE
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# COMPUTE THE EIGENVALUES
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [ ]:
# CREATE TWO NUMPY ARRAYS OF SHAPE (2, 3) AND (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# PERFORM MATRIX MULTIPLICATION
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [6]:
# CREATE A NUMPY ARRAY OF SHAPE (3, 3) WITH VALUES FROM 1 TO 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# RESHAPE THE ARRAY TO SHAPE (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# RESHAPE THE ARRAY TO SHAPE (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (5, 5) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# FLATTEN THE ARRAY
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# RESHAPE THE ARRAY BACK TO (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (5, 5) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# USE FANCY INDEXING TO EXTRACT THE ELEMENTS AT THE CORNERS OF THE ARRAY
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [ ]:
# CREATE A NUMPY ARRAY OF SHAPE (4, 4) FILLED WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# USE BOOLEAN INDEXING TO SET ALL ELEMENTS GREATER THAN 10 TO 10
array[array > 10] = 10
print("Modified array:")
print(array)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [ ]:
# CREATE A STRUCTURED ARRAY WITH FIELDS 'NAME', 'AGE', AND 'WEIGHT'
data_type = [("name", "U10"), ("age", "i4"), ("weight", "f4")]
data = np.array(
    [("Alice", 25, 55.5), ("Bob", 30, 85.3), ("Charlie", 20, 65.2)], dtype=data_type
)
print("Original array:")
print(data)

# SORT THE ARRAY BY AGE
sorted_data = np.sort(data, order="age")
print("Sorted array by age:")
print(sorted_data)

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [ ]:
# CREATE A STRUCTURED ARRAY WITH FIELDS 'X' AND 'Y'
data_type = [("x", "i4"), ("y", "i4")]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# COMPUTE THE EUCLIDEAN DISTANCE BETWEEN EACH PAIR OF POINTS
distances = np.sqrt(
    (data["x"][:, np.newaxis] - data["x"]) ** 2
    + (data["y"][:, np.newaxis] - data["y"]) ** 2
)
print("Euclidean distances:")
print(distances)

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [ ]:
import numpy.ma as ma

# CREATE A MASKED ARRAY OF SHAPE (4, 4) WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# COMPUTE THE SUM OF THE UNMASKED ELEMENTS
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.


In [ ]:
# CREATE A MASKED ARRAY OF SHAPE (3, 3) WITH RANDOM INTEGERS
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# REPLACE THE MASKED ELEMENTS WITH THE MEAN OF THE UNMASKED ELEMENTS
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)